### ISSUE TITLE
Aplicabilidade do atomic design

### ISSUE THREAD

**Issue by rafaelrpbelo** [elemencast/episodios#1]
Olá, acompanhei os podcasts e fiquei realmente curioso à respeito de como aplicar atomic design em uma real world application.

Pelo o que entendi, existem as seguintes camadas:

```
átomos > moléculas > organismos > templates > páginas
```

Até aí tudo certo! Eu entendi cada camada como abstrações, sendo o átomo a menor delas. Agora digamos que, seguindo o modelo biológico nós teríamos uma hierarquia, porém eu poderia ter páginas com átomos, que não estariam obrigatoriamente inclusos em uma moléculas, ou ainda que, eu poderia ter moléculas em um template, sem a necessidade de um organismo. Isso é possível?

*PS: Quais as recomendações para leitura, além do [book](http://atomicdesign.bradfrost.com/) do criador. Onde eu posso encontrar repositórios públicos com exemplos práticos?*

**Comment by luiguild** [comment]
Fala @rafaelrpbelo!

Primeiramente muito obrigado por vir até pra conversarmos mais sobre AD.

Assim como eu disse no episódio 2 do elemencast (https://elemencast.github.io/#/episodios/2) e postei aqui no Medium (https://medium.com/@luiguild/t%C3%A1-quero-separar-tudo-em-componentes-como-ficam-os-entreg%C3%A1veis-a035e099d5fc)

Se você ficou pensando sobre como pode ser chato seguir a ordem do Atomic Design, saiba que não é obrigatório seguir o fluxo proposto pela **metodologia.**

Se você precisar ir de ‘página’ pra ‘átomo’ diretamente, tudo bem! Só não esqueça que o fluxo do dado é sempre do menor para o maior e que as chamadas das funções partem sempre das maiores pras menores. Ou seja, você não pode fazer um átomo chamar outro átomo que chama outro átomo, que chama mais um outro átomo… Não faz sentido isso… Você precisa orquestrar essas chamadas.

O lance é que tipo, se você precisar ir ```template > átomo```, tudo bem, não tem problema e também tem o fato de que se você quiser, não precisa usar esses nomes também... O nome das unidades podem ser discutidas em grupos (ou dentro da sua cachola mesmo) e aí você pode usar os nomes que quiser.

Em algum momento isso vai acontecer, não precisa ficar preocupado com isso 😄

**Comment by rafaelrpbelo** [comment]
Opa @luiguild!

Valeu pelas dicas. Este post do medium tinha passado despercebido por mim, vou da uma lida nele e vou tentar aplicar a metodologia, depois voltarei aqui para discutirmos algo, caso apareça alguma dúvida.

👍 😉
